version: '3.1'

services:
  mysql:
    image: mysql
    container_name: "mysql_db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
